<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260108181316 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE client ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE dc_order ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN dc_order.payload_served IS \'\'');
        $this->addSql('COMMENT ON COLUMN dc_order.api_response IS \'\'');
        $this->addSql('ALTER INDEX idx_dbbc0d8a333625d8 RENAME TO IDX_DBBC0D8A8D9F6D38');
        $this->addSql('ALTER TABLE dc_user ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE dc_user ALTER roles SET NOT NULL');
        $this->addSql('ALTER TABLE deputy ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE document ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE client ALTER id DROP IDENTITY');
        $this->addSql('DROP INDEX UNIQ_450EF9F7551F0F81');
        $this->addSql('ALTER TABLE dc_order ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN dc_order.payload_served IS \'(DC2Type:json_array)\'');
        $this->addSql('COMMENT ON COLUMN dc_order.api_response IS \'(DC2Type:json_array)\'');
        $this->addSql('ALTER TABLE dc_user ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE dc_user ALTER roles DROP NOT NULL');
        $this->addSql('ALTER TABLE deputy ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE document ALTER id DROP IDENTITY');
        $this->addSql('ALTER INDEX idx_dbbc0d8a8d9f6d38 RENAME TO idx_dbbc0d8a333625d8');
    }
}
