version: 2

updates:

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "10:00"
      timezone: "Europe/London"
    commit-message:
      prefix: "#patch"  
    pull-request-branch-name:
      separator: "-"

  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
      time: "10:00"
      timezone: "Europe/London"
    commit-message:
      prefix: "#patch"  
    pull-request-branch-name:
      separator: "-"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "10:00"
      timezone: "Europe/London"
    commit-message:
      prefix: "#patch"
    pull-request-branch-name:
      separator: "-"