repo:
  - any: ["./*"]

pipeline:
  - any: [".github/workflows/*"]

web:
  - any: ["serve-web/**/*"]

documentation:
  - any: ["docs/**/*"]

infrastructure:
  - any: ["terraform/**/*"]

scripts:
  - any: ["scripts/**/*"]
