FROM nginx:latest
# todo - move to alpine
# todo - make sure paths for default.conf and app.conf are the same

RUN rm -f /etc/nginx/conf.d/default.conf
COPY misc/config/app.conf /etc/nginx/conf.d/app.conf

