FROM php:7.2.7-fpm-alpine3.7

RUN apk --no-cache add bash nano tree

WORKDIR /app

RUN php -r "readfile('http://getcomposer.org/installer');" | php -- --install-dir=/usr/bin/ --filename=composer && \
    composer global require hirak/prestissimo
