FROM php:7.2.7-fpm-alpine3.7

RUN apk --no-cache add bash nano tree

WORKDIR /app

RUN php -r "readfile('http://getcomposer.org/installer');" | php -- --install-dir=/usr/bin/ --filename=composer && \
    composer global require hirak/prestissimo

# todo - consider where this will live
# COMPOSER run scripts (e.g. parameters.yml)
#RUN  composer run-script post-install-cmd --no-interaction
#RUN  composer dump-autoload --optimize

