# ###############################################################################
# This file is owned by WebOps. Do not merge to master without WebOps input first
# ###############################################################################

FROM alpine:3.8

RUN apk --update --no-cache add \
  nodejs-npm bash tree nano

WORKDIR /app

USER root

RUN npm config set unsafe-perm true && \
    npm -g set progress=false && \
    npm install -g gulp@3.9.1
