FROM php:7.2.7-fpm-alpine3.7

# install packages via APK
# https://github.com/gliderlabs/docker-alpine/blob/master/docs/usage.md
RUN apk --no-cache add \
  nodejs

# install composer
RUN php -r "readfile('http://getcomposer.org/installer');" | php -- --install-dir=/usr/bin/ --filename=composer

# copy php.ini config
COPY misc/config/php.ini /usr/local/etc/php/

WORKDIR /app

COPY package.json /app/
RUN  npm -g set progress=false
RUN  npm install -g gulp@3.9.1
RUN  npm install

# composer install
RUN composer global require hirak/prestissimo
COPY composer.json /app/
COPY composer.lock /app/
RUN  composer install --prefer-dist --no-interaction --no-scripts -o

# add dirs
ADD . /app

# COMPOSER run scripts (e.g. parameters.yml)
RUN  composer run-script post-install-cmd --no-interaction
RUN  composer dump-autoload --optimize

# Assets processing
RUN gulp

# cache clean
RUN mkdir -p /tmp/app-cache
RUN mkdir -p /var/log/app
RUN chown www-data:www-data -R /tmp/app-cache /var/log/app

