version: '3'
services:
  app:
    environment:
      APP_ENV: 'dev'
      APP_DEBUG: 'true'
    env_file:
      - .env.local
    volumes:
      - ./serve-web:/var/www
      - ./serve-web/var:/www/var/
