version: '3'
services:
  app:
    volumes:
      - ./serve-web:/var/www
      - ./serve-web/var:/www/var/
  api:
    build:
      context: ./serve-api
      dockerfile: docker/Dockerfile.dev
    volumes:
      - ./serve-api:/api
    command: air
