---
version: '3'

services:
  app:
    build:
      args:
        WITH_XDEBUG: 'true'
    environment:
      APP_ENV: 'dev'
      APP_DEBUG: 'true'
    volumes:
      - ./serve-web/docker/app/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
