services:
  aws:
    image: infrastructureascode/aws-cli@sha256:891db48126b0f044f06263521acbd611dfa31aa9e549fed23b0b3ef890082b36
    environment:
      - AWS_ACCESS_KEY_ID=foo
      - AWS_SECRET_ACCESS_KEY=bar
    entrypoint:
      - aws
    working_dir: /var/www
    volumes:
      - ./serve-web:/var/www
    depends_on:
      - localstack

  loadbalancer:
    image: jwilder/nginx-proxy:1.11-alpine@sha256:2649b448d45147cb8b35ecfcb5fc719dd601cba7bcb33cb12e547aeadb2d5273
    ports:
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./serve-web/certs:/etc/nginx/certs
      - ./serve-web/docker/loadbalancer/my_proxy.conf:/etc/nginx/conf.d/my_proxy.conf:ro
    depends_on:
      web:
        condition: service_started
      app:
        condition: service_healthy
    environment:
      DHPARAM_SKIP: true
      TRUST_DOWNSTREAM_PROXY: true
      DEFAULT_HOST: web
      CERT_NAME: web.crt

  web:
    build:
      context: ./serve-web
      dockerfile: docker/web/Dockerfile
      args:
        APP_HOST_ARG: ${APP_HOST_LOCAL_ENV:-app}
        APP_PORT_ARG: ${APP_PORT_LOCAL_ENV:-9000}
    image: 311462405659.dkr.ecr.eu-west-1.amazonaws.com/serve-opg/web:latest
    ports:
      - 80:80
    depends_on:
      app:
        condition: service_healthy
    environment:
      VIRTUAL_HOST: web
    volumes:
      - ./serve-web/public:/var/www/public

  app:
    build:
      context: ./serve-web
      dockerfile: docker/app/Dockerfile
    image: 311462405659.dkr.ecr.eu-west-1.amazonaws.com/serve-opg/app:latest
    ports:
      - 9000:9000
    env_file:
      - ./serve-web/.env
    # Setting here rather than .env to stop them being overwritten during build steps on prod
    environment:
      - APP_SECRET=aFakeSecret
      - AWS_ACCESS_KEY_ID=foo
      - AWS_SECRET_ACCESS_KEY=bar
      - AWS_REGION=eu-west-1
      - BEHAT_PASSWORD=Abcd1234
      - DC_S3_ENDPOINT=http://localstack:4566
      - DYNAMODB_ENDPOINT=http://localstack:4566
      - AWS_EVENTBRIDGE_ENDPOINT=http://localstack:4566
      - FIXTURES_ENABLED=true
      - OS_PLACES_API_KEY=DUMMY_KEY
      - SIRIUS_PUBLIC_API_PASSWORD=FAKE_API_PASSWORD
      - ENVIRONMENT_NAME=local
      - USE_EVENT_BUS=false
      - VIRTUAL_HOST=app
    depends_on:
      postgres:
        condition: service_healthy
      localstack:
        condition: service_healthy
      sirius-api:
        condition: service_started
    healthcheck:
      test: [ "CMD-SHELL", "/usr/local/bin/health-check.sh" ]
      interval: 5s
      timeout: 10s
      start_period: 5s
      retries: 3

  backup:
    build:
      context: ./disaster-recovery/backup
      dockerfile: Dockerfile
    image: 311462405659.dkr.ecr.eu-west-1.amazonaws.com/serve-opg/backup:latest

  orchestration:
    build:
      context: ./orchestration
      dockerfile: Dockerfile
    image: 311462405659.dkr.ecr.eu-west-1.amazonaws.com/serve-opg/orchestration:latest

  # TODO - Work out why upgrades to prism break behat
  sirius-api:
    image: stoplight/prism:4.4.3@sha256:5f590fcfe55e0c4a97287465cbf84b31712ad439358d35b5b92b303fbe06e7a8
    ports:
      - 4010:4010
    volumes:
      - ./serve-web:/tmp
    command:
      - mock
      - /tmp/api.public.v1.yaml
      - -h
      - 0.0.0.0
      - --dynamic

  localstack:
    build:
      context: .
      dockerfile: local-setup/localstack/Dockerfile
    ports:
      - "4566-4583:4566-4583"
    environment:
      - SERVICES=s3,dynamodb,kms,secretsmanager,events,sqs
      - DATA_DIR=/tmp/localstack/data
      - S3_SKIP_KMS_KEY_VALIDATION=1
      - KMS_PROVIDER=local-kms
      - LAMBDA_REMOTE_DOCKER=0
      - DEBUG=1
    healthcheck:
      test: [ "CMD", "bash", "-c", "/tmp/healthcheck.sh" ]
      interval: 5s
      timeout: 10s
      start_period: 10s

  postgres:
    image: postgres:14.23@sha256:d462928b1898dd74b749ef486797968828c1e7fc9befb5e5ca03a33bfbc32d64
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: serve-opg
      POSTGRES_USER: serve-opg
      POSTGRES_PASSWORD: dcdb2018!
      POSTGRES_API_DB_USER: serve-opg-api
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d serve-opg -U serve-opg" ]
      interval: 3s
      timeout: 10s
    restart: always

  npm:
    image: node:25-alpine@sha256:bdf2cca6fe3dabd014ea60163eca3f0f7015fbd5c7ee1b0e9ccb4ced6eb02ef4
    environment:
      PATH: /node_modules/.bin:$PATH
    working_dir: /var/www
    volumes:
      - ./serve-web/node_modules:/var/www/node_modules
      - ./serve-web:/var/www

  behat:
    build:
      context: ./serve-web
      dockerfile: docker/app/Dockerfile
    image: 311462405659.dkr.ecr.eu-west-1.amazonaws.com/serve-opg/app:latest
    volumes:
      - ./serve-web:/var/www
    working_dir: /var/www
    entrypoint:
      - vendor/bin/behat
      - -c
      - behat.yml.dist
      - --suite=local
      - --stop-on-failure
      - --no-interaction
    env_file:
      - ./serve-web/.env
    environment:
      APP_ENV: 'test'
      BEHAT_PARAMS: '{"extensions" : {"Behat\\MinkExtension" : {"base_url" : "https://loadbalancer"}}}'
      BEHAT_PASSWORD: 'Abcd1234'
      ENVIRONMENT_NAME: local

  qa:
    image: jakzal/phpqa:alpine@sha256:aa5b47171c146a8b4071a8ca39d3939de428b6661795712fd928cabf105ce002
    volumes:
      - ./serve-web:/var/www:ro
    working_dir: /var/www
