version: '3'
services:
    app:
        build:
            args:
                WITH_XDEBUG: 'false'
        environment:
            APP_ENV: 'dev'
            APP_DEBUG: 'true'
        env_file:
            - .env.local
