version: '3'
services:
  app:
    environment:
      APP_ENV: 'dev'
      APP_DEBUG: 'false'
    volumes:
      - ./serve-web:/var/www
      - ./serve-web/var:/www/var/

  api:
    build:
      context: ./serve-api
      dockerfile: docker/Dockerfile.dev
    volumes:
      - ./serve-api:/api
    tty: true
