---
version: "3"

services:
  aws:
    image: infrastructureascode/aws-cli
    #    Setting here rather than .env to stop them being overwritten during build steps on prod
    environment:
      - AWS_ACCESS_KEY_ID=foo
      - AWS_SECRET_ACCESS_KEY=bar
    entrypoint:
      - aws
    working_dir: /var/www
    volumes:
      - ./serve-web:/var/www
    depends_on:
      - localstack

  loadbalancer:
    image: jwilder/nginx-proxy:alpine-0.7.0
    ports:
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./serve-web/certs:/etc/nginx/certs
      - ./serve-web/docker/loadbalancer/my_proxy.conf:/etc/nginx/conf.d/my_proxy.conf:ro
    depends_on:
      - web
    environment:
      DHPARAM_GENERATION: "false"
      DEFAULT_HOST: localhost
      CERT_NAME: web.crt

  web:
    build:
      context: ./serve-web
      dockerfile: docker/web/Dockerfile
    image: 311462405659.dkr.ecr.eu-west-1.amazonaws.com/serve-opg/web:latest
    depends_on:
      - app
    environment:
      APP_HOST: app
      APP_PORT: 9000
      NGINX_LOG_LEVEL: warn
      VIRTUAL_HOST: web

    volumes:
      - ./serve-web/public:/var/www/public

  app:
    build:
      context: ./serve-web
      dockerfile: docker/app/Dockerfile
    image: 311462405659.dkr.ecr.eu-west-1.amazonaws.com/serve-opg/app:latest
    env_file:
      - .env
    #    Setting here rather than .env to stop them being overwritten during build steps on prod
    environment:
      - AWS_ACCESS_KEY_ID=foo
      - AWS_SECRET_ACCESS_KEY=bar
      - DC_BEHAT_CONTROLLER_ENABLED=1
      - DC_S3_ENDPOINT=http://localstack:4572
      - DYNAMODB_ENDPOINT=http://localstack:4569
      - OS_PLACES_API_KEY=DUMMY_KEY
      - SIRIUS_PUBLIC_API_PASSWORD=FAKE_API_PASSWORD
      - APP_SECRET=aFakeSecret
      - FIXTURES_ENABLED=true
      - BEHAT_PASSWORD=Abcd1234
    depends_on:
      - localstack
      - postgres
      - sirius-api
    volumes:
      - ./serve-web:/var/www
      - ./serve-web/var:/www/var/

  sirius-api:
    image: stoplight/prism:latest
    ports:
      - 4010:4010
    volumes:
      - ./serve-web:/tmp
    command:
      - mock
      - /tmp/api.public.v1.yaml
      - -h
      - 0.0.0.0
      - --dynamic

  localstack:
    image: localstack/localstack:0.9.1
    environment:
      - SERVICES=s3:4572,dynamodb:4569
      - DATA_DIR=/tmp/localstack/data
      - DEFAULT_REGION=eu-west-1
    volumes:
      - ./serve-web/localstack-data:/tmp/localstack/data

  postgres:
    image: postgres:9.6-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: serve-opg
      POSTGRES_USER: serve-opg
      POSTGRES_PASSWORD: dcdb2018!

  yarn:
    image: node:14.17-stretch
    environment:
      PATH: /node_modules/.bin:$PATH
    working_dir: /var/www
    volumes:
      - ./serve-web/node_modules:/var/www/node_modules
      - ./serve-web:/var/www
    entrypoint: ["yarn"]

  behat:
    image: php:7.4-fpm-alpine
    volumes:
      - ./serve-web:/var/www
      - ./serve-web/features/screenshots:/tmp/behat
    working_dir: /var/www
    entrypoint:
      - vendor/bin/behat
      - -c
      - behat.yml.dist
      - --suite=local
      - --stop-on-failure
      - --no-interaction
    env_file:
      - .env
    depends_on:
      - loadbalancer
    environment:
      BEHAT_PARAMS: '{"extensions" : {"Behat\\MinkExtension" : {"base_url" : "https://loadbalancer"}}}'

  qa:
    image: jakzal/phpqa:alpine
    volumes:
      - ./serve-web:/var/www:ro
    working_dir: /var/www

  waitforit:
    build:
      context: ./serve-web
      dockerfile: docker/waitforit/Dockerfile

  api:
    image: api
    build: ./serve-api
    ports:
      - 9000:9000
