# ###############################################################################
# This file is owned by WebOps. Do not merge to master without WebOps input first
# ###############################################################################


FROM php:7.2.7-fpm-alpine3.7

#ARG=HOST_USER_ID
#ARG=HOST_GROUP_ID

RUN apk --no-cache add bash nano tree shadow

WORKDIR /app

RUN groupmod -g 1000 www-data && \
    usermod -u 1000 -g 1000 www-data

RUN php -r "readfile('http://getcomposer.org/installer');" | php -- --install-dir=/usr/bin/ --filename=composer && \
    composer global require hirak/prestissimo

USER www-data
