# ###############################################################################
# This file is owned by WebOps. Do not merge to master without WebOps input first
# ###############################################################################

FROM nginx:latest
# todo - move to alpine
# todo - make sure paths for default.conf and app.conf are the same

RUN groupmod -g 1000 www-data && \
    usermod -u 1000 -g 1000 www-data

RUN rm -f /etc/nginx/conf.d/default.conf
COPY misc/config/app.conf /etc/nginx/conf.d/app.conf
