doctrine_migrations:
    migrations_paths:
        "DoctrineMigrations": "%kernel.project_dir%/src/Migrations"
    organize_migrations: false # Version >=1.2 Possible values are: "BY_YEAR", "BY_YEAR_AND_MONTH", false
    storage:
        # Default (SQL table) metadata storage configuration
        table_storage:
            table_name: "migration_versions"
            version_column_name: "version"
            version_column_length: 1024
            executed_at_column_name: "executed_at"
