FROM golang:1.18-alpine

# Working directory
WORKDIR /app

COPY go.mod .
COPY go.sum .

RUN apk update && apk --update --no-cache add \ 
    git \
    ca-certificates \
    && rm -rf /var/cache/apk/*
RUN apk --no-cache add tzdata

# Go envs
RUN unset GOPATH
ENV GOOS=linux GOARCH=amd64 CGO_ENABLED=0

RUN go mod download && go mod verify

# Live reload for Go
RUN go install github.com/cosmtrek/air@latest