#!/bin/bash
set -e

POSTGRES="psql --username ${POSTGRES_USER}"

echo "Creating database role: ${POSTGRES_API_DB_USER}"

$POSTGRES <<-EOSQL
CREATE USER "${POSTGRES_API_DB_USER}" WITH CREATEDB SUPERUSER CREATEROLE REPLICATION BYPASSRLS PASSWORD '${POSTGRES_PASSWORD}';
EOSQL