on:
  workflow_call:
    inputs:
      branch_name:
        description: "Name of the branch doing the build"
        required: true
        type: string
      tag:
        description: "Tag for docker image"
        required: false
        default: "latest"
        type: string
    secrets:
      snyk_token:
        required: true

defaults:
  run:
    shell: bash

jobs:
  build_and_push_containers:
    strategy:
      fail-fast: false
      matrix:
        include:
          -   svc_name: "app"
          -   svc_name: "web"
          -   svc_name: "backup"
          -   svc_name: "orchestration"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

      - name: SLSA
        uses: ministryofjustice/devsecops-actions/sca/slsa@4cd163be7859cd130800d6719d925318826038ea
        with:
          working-directory: serve-web

      - name: Build Containers
        env:
            APP_HOST_LOCAL_ENV: 127.0.0.1
            APP_PORT_LOCAL_ENV: 9000
            CONTAINER: ${{ matrix.svc_name }}
        run: |
          # Create composer and JS dependencies
          docker compose run --rm app composer install --no-interaction
          docker compose run --rm --entrypoint "npm ci --ignore-scripts" npm
          docker compose run --rm --entrypoint "npm run build" npm
          # Build all apps
          docker compose build "${CONTAINER}"

      - name: Configure OIDC AWS Credentials Pull
        uses: aws-actions/configure-aws-credentials@61815dcd50bd041e203e49132bacad1fd04d2708 # v5
        with:
          aws-region: eu-west-1
          role-to-assume: arn:aws:iam::${{ vars.MANAGEMENT_ACCOUNT }}:role/serve-gh-actions-ecr-pull
          role-duration-seconds: 900
          role-session-name: ga-ecr-pull-serve

      - uses: aws-actions/amazon-ecr-login@d539f0932e70871a027e9d5a9d8fc38589180a64 # v2.1.6
        id: login-ecr-pull
        with:
          registries: ${{ vars.MANAGEMENT_ACCOUNT }}
          mask-password: "true"

      - name: Run Snyk Scan
        id: snyk_scan
        uses: ministryofjustice/opg-github-actions/actions/snyk-scan@9e756945a9e2b6ac5dc81473b01f8b38600e6ed6 # v4.8.6
        with:
          SNYK_TEST_IMAGE: ${{ vars.MANAGEMENT_ACCOUNT }}.dkr.ecr.eu-west-1.amazonaws.com/serve-opg/${{ matrix.svc_name }}:latest
          SNYK_TOKEN: ${{ secrets.snyk_token }}
          snyk_test_args: "--severity-threshold=high"
          sarif_filepath: ./test-results
          sarif_filename: snyk-results.sarif
          snyk_policy_path: ${{ github.workspace }}/.github/.snyk

      - name: Upload SNYK scan results to GitHub Security tab
        if: steps.snyk_scan.outcome == 'success' && hashFiles('test-results/snyk-results.sarif') != ''
        uses: github/codeql-action/upload-sarif@b8bb9f28b8d3f992092362369c57161b755dea45 # v4.35.0
        with:
          sarif_file: test-results/snyk-results.sarif
          category: ${{ matrix.svc_name }}

      - name: Configure OIDC AWS Credentials Push
        uses: aws-actions/configure-aws-credentials@61815dcd50bd041e203e49132bacad1fd04d2708 # v5
        with:
          aws-region: eu-west-1
          role-to-assume: arn:aws:iam::${{ vars.MANAGEMENT_ACCOUNT }}:role/serve-gh-actions-ecr-push
          role-duration-seconds: 900
          role-session-name: ga-ecr-push-serve

      - uses: aws-actions/amazon-ecr-login@d539f0932e70871a027e9d5a9d8fc38589180a64 # v2.1.6
        id: login-ecr
        with:
          registries: ${{ vars.MANAGEMENT_ACCOUNT }}
          mask-password: "true"

      - name: Show build tag
        env:
          IMAGE_TAG: ${{ inputs.tag }}
        run: echo "Tag to use - ${IMAGE_TAG}"

      - name: Push Containers
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          BRANCH_NAME: ${{ inputs.branch_name }}
          TAG: ${{ inputs.tag }}
          CONTAINER: ${{ matrix.svc_name }}
        run: |
          echo "Running on branch ${BRANCH_NAME}"

          docker tag "${ECR_REGISTRY}/serve-opg/${CONTAINER}:latest" "${ECR_REGISTRY}/serve-opg/${CONTAINER}:${TAG}"

          if [ "${BRANCH_NAME}" == "main" ]; then
            docker tag "${ECR_REGISTRY}/serve-opg/${CONTAINER}:latest" "${ECR_REGISTRY}/serve-opg/${CONTAINER}:main-${TAG}"
            echo "Pushing all tags as on branch: ${BRANCH_NAME}"
            docker push --all-tags "${ECR_REGISTRY}/serve-opg/${CONTAINER}"
          else
            echo "Pushing branch ${BRANCH_NAME} tags only"
            docker push "${ECR_REGISTRY}/serve-opg/${CONTAINER}:${TAG}"
          fi
