on:
  workflow_call:
    inputs:
      branch_name:
        description: "Name of the branch doing the build"
        required: true
        type: string
      tag:
        description: "Tag for docker image"
        required: false
        default: "latest"
        type: string

defaults:
  run:
    shell: bash

jobs:
  build_and_push_containers:
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b32f140b0c872d58512e0a66172253c302617b90

      - name: install aws cli
        uses: unfor19/install-aws-cli-action@46282f151073130d90347412d9c4ef0640177f22

      - name: Build Containers
        run: |
          # Create composer and JS dependencies
          docker compose run --rm app composer install --no-interaction
          docker compose run --rm yarn install --frozen-lockfile
          docker compose run --rm yarn build
          # Build all apps
          docker compose build web app

      - name: Configure OIDC AWS Credentials
        uses: aws-actions/configure-aws-credentials@b140ab7b246475139f89894ebae4ba00bd5b374e
        with:
          aws-region: eu-west-1
          role-to-assume: arn:aws:iam::311462405659:role/serve-gh-actions-ecr-push
          role-duration-seconds: 900
          role-session-name: ga-ecr-push-serve

      - name: ECR Login
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@ae939c465be2882e7fe4d2e2e4083de854a59655
        with:
          registries: 311462405659

      - name: Show build tag
        env:
          IMAGE_TAG: ${{ inputs.tag }}
        run: echo "Tag to use - ${IMAGE_TAG}"

      - name: Push Containers
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          BRANCH: ${{ inputs.branch_name }}
        run: |
          docker tag $ECR_REGISTRY/serve-opg/app:latest $ECR_REGISTRY/serve-opg/app:${{ inputs.tag }}
          docker tag $ECR_REGISTRY/serve-opg/web:latest $ECR_REGISTRY/serve-opg/web:${{ inputs.tag }}

          if [ "$BRANCH_NAME" == "main" ]; then
            # We want all of the tags pushed
            docker push --all-tags $ECR_REGISTRY/serve-opg/app
            docker push --all-tags $ECR_REGISTRY/serve-opg/web
          else
            docker push $ECR_REGISTRY/serve-opg/app:${{ inputs.tag }}
            docker push $ECR_REGISTRY/serve-opg/web:${{ inputs.tag }}
          fi
