name: "Snyk IAC scan"

defaults:
  run:
    shell: bash

on:
  workflow_call:
    secrets:
      snyk_token:
        required: true

permissions:
  actions: none
  checks: none
  contents: write
  deployments: none
  id-token: write
  issues: none
  packages: none
  pull-requests: read
  repository-projects: none
  security-events: write
  statuses: none

jobs:
  snyk_iac_scan:
    name: Run Snyk IAC scan
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: account
            terraform_configuration_path: ./terraform/account/
          - name: environment
            terraform_configuration_path: ./terraform/environment/

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Configure OIDC AWS Credentials Pull
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
        with:
          aws-region: eu-west-1
          role-to-assume: arn:aws:iam::${{ vars.MANAGEMENT_ACCOUNT }}:role/serve-gh-actions-ecr-pull
          role-duration-seconds: 900
          role-session-name: ga-ecr-pull-serve

      - uses: aws-actions/amazon-ecr-login@fa648b43de3d4d023bcb3f89ed6940096949c419 # v2.1.5
        id: login-ecr
        with:
          registries: ${{ vars.MANAGEMENT_ACCOUNT }}
          mask-password: "true"

      - name: Snyk IaC ${{ matrix.name }}
        id: snyk_iac
        uses: ministryofjustice/opg-github-actions/actions/snyk-iac@83663a5235330cc2193319b25d559885610c6bd5 # v4.8.4
        with:
          iac_test_directory: "${{ matrix.terraform_configuration_path }}"
          SNYK_TOKEN: ${{ secrets.snyk_token }}
          snyk_test_args: "--severity-threshold=high"
          snyk_policy_path: "${{ matrix.terraform_configuration_path }}.snyk"

      - name: Upload Snyk IaC results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@38697555549f1db7851b81482ff19f1fa5c4fedc # v4.34.1
        if: always()
        with:
          category: "IaC-${{matrix.name}}"
          sarif_file: "test-results/snyk.sarif"
