name: "Snyk IAC scan"

defaults:
  run:
    shell: bash

on:
  workflow_call:
    secrets:
      snyk_token:
        required: true

permissions:
  id-token: write
  security-events: write

jobs:
  snyk_iac_scan:
    name: Run Snyk IAC scan
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: account
            terraform_configuration_path: ./terraform/account/
          - name: environment
            terraform_configuration_path: ./terraform/environment/

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
            persist-credentials: false

      - name: Configure OIDC AWS Credentials Pull
        uses: aws-actions/configure-aws-credentials@e1253824e5c10ff9df46874f81ed3ec929e19cfd # v6
        with:
          aws-region: eu-west-1
          role-to-assume: arn:aws:iam::${{ vars.MANAGEMENT_ACCOUNT }}:role/serve-gh-actions-ecr-pull
          role-duration-seconds: 900
          role-session-name: ga-ecr-pull-serve

      - uses: aws-actions/amazon-ecr-login@03f1aad4c6c7ffd436567f42f9384779290529bd # v2.1.7
        id: login-ecr
        with:
          registries: ${{ vars.MANAGEMENT_ACCOUNT }}
          mask-password: "true"

      - name: Snyk IaC ${{ matrix.name }}
        id: snyk_iac
        uses: ministryofjustice/opg-github-actions/actions/snyk-iac@bec642d35dd1f72cd2986722b243be50aaf4bf8c # v4.10.1
        with:
          iac_test_directory: "${{ matrix.terraform_configuration_path }}"
          SNYK_TOKEN: ${{ secrets.snyk_token }}
          snyk_test_args: "--severity-threshold=low"
          snyk_policy_path: "${{ matrix.terraform_configuration_path }}.snyk"

      - name: Upload Snyk IaC results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@7211b7c8077ea37d8641b6271f6a365a22a5fbfa # v4.36.0
        if: always()
        with:
          category: "IaC-${{matrix.name}}"
          sarif_file: "test-results/snyk.sarif"
