name: "[Tag] Releasable Image as Release"

on:
  workflow_call:
    inputs:
      release_tag:
        required: true
        type: string
      current_tag:
        required: true
        type: string
      

jobs:
  tag_releasable_image:
    strategy:
      fail-fast: false
      matrix:
        include:
          -   svc_name: "app"
          -   svc_name: "web"
          -   svc_name: "backup"
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials for ECR tagging
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1
          role-to-assume: arn:aws:iam::311462405659:role/serve-gh-actions-ecr-push
          role-session-name: github-actions-ecr-tagger
          role-duration-seconds: 900

      - name: Tag "releasable" image with new release tag
        env:
          RELEASE_TAG: ${{ inputs.release_tag }}
          REPOSITORY: "serve-opg"
          CURRENT_TAG: ${{ inputs.current_tag }}
        run: |
          REPO_NAME=${REPOSITORY}/${{ matrix.svc_name }}
          
          aws ecr batch-get-image --repository-name "${REPO_NAME}" --image-ids imageTag="${CURRENT_TAG}" --query 'images[0].imageManifest' --output text > manifest.json
          
          aws ecr put-image --repository-name "${REPO_NAME}" --image-tag "${RELEASE_TAG}" --image-manifest file://manifest.json

