on:
  workflow_call:

jobs:
  test_web:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5
        - name: Build Dependencies
          run: make dependencies

        - name: Run Unit Tests
          run: |
            ./serve-web/generate_certs.sh
            make unit-tests

        - name: Run Integrations Tests
          run: |
            make behat-tests
