on:
  workflow_call:

jobs:
  test_web:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        - name: Build Dependencies
          run: make dependencies

        - name: Run Unit Tests
          run: |
            ./serve-web/generate_certs.sh
            make unit-tests

        - name: Run Integrations Tests
          run: |
            make behat-tests
