on:
  workflow_call:

jobs:
  test_api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./serve-api
    env:
      TEST_RESULTS: /tmp/test_results
    services:
      postgres:
        image: postgres
        # Not real passwords
        env:
          POSTGRES_HOST: localhost
          POSTGRES_DB: serve-opg
          POSTGRES_USER: serve-opg
          POSTGRES_PASSWORD: dcdb2018!
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
      - uses: actions/setup-python@v4
        with:
            python-version: '3.10'
      - name: resolve go cache
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-
      - name: resolve go dependencies
        run: go mod download
      - name: Create test result directory
        run: mkdir -p ${{ env.TEST_RESULTS }}
      - name: Setup gotestsum
        run: go install gotest.tools/gotestsum@v1.8.2
      - name: Add GOPATH
        run: echo "$GOPATH/bin" >> $GITHUB_PATH
      - name: run unit tests
        run: gotestsum --junitfile unit-tests.xml
