name: "[Scheduled] Cycle DB Secrets"

on:
  schedule:
    # 1:30AM from Monday to Friday
    - cron: "30 1 * * 1-5"

permissions:
  id-token: write
  contents: read
  security-events: none
  pull-requests: none
  actions: none
  checks: none
  deployments: none
  issues: none
  packages: none
  repository-projects: none
  statuses: none

jobs:
  rotate_secrets_preproduction:
    name: rotate secrets for preproduction account
    uses: ./.github/workflows/_cycle-secrets.yml
    with:
      account_environment: preproduction
      secret_type: database

  rotate_secrets_production:
    name: rotate secrets for production account
    uses: ./.github/workflows/_cycle-secrets.yml
    needs:
      - rotate_secrets_preproduction
    with:
      account_environment: production
      secret_type: database
