on:
  workflow_call:

jobs:
  test_web:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Set up Python 3.10.9
          uses: actions/setup-python@v4
          with:
            python-version: 3.10.9
        - name: Build Dependencies
          run: |
            # Create the s3 buckets
            # & wait for the server to become available
            docker-compose up -d localstack

            docker-compose run --rm waitforit -address=http://localstack:4566 -debug -timeout=30
            docker-compose run --rm aws --endpoint-url=http://localstack:4566 s3 mb s3://sirius-test-bucket
            docker-compose run --rm aws --endpoint-url=http://localstack:4566 s3 mb s3://test-bucket

            # Create dynamodb tables
            docker-compose run --rm aws --region eu-west-1 --endpoint-url=http://localstack:4566 dynamodb create-table --cli-input-json file://attempts_table.json
            docker-compose run --rm aws --region eu-west-1 --endpoint-url=http://localstack:4566 dynamodb create-table --cli-input-json file://sessions_table.json

            # Triggers Symfony Flex to run recipes during composer install - required for phpunit-bridge
            rm -rf ./serve-web/vendor
            rm -rf ./serve-web/symfony.lock

            # Vendor php dependencies
            docker-compose run --rm app composer install --no-interaction

            # Install js dependencies
            docker-compose run --rm yarn install --frozen-lockfile

            # Generate static assets
            docker-compose run --rm yarn build-dev

            # Removes boilerplate feature test added during Symfony Flex recipe for behat
            rm -rf ./serve-web/features/demo.feature

        - name: Run Unit Tests
          run: |
            ./serve-web/generate_certs.sh
            docker-compose -f docker-compose.test.yml -f docker-compose.yml up --build -d loadbalancer
            docker-compose run --rm waitforit -address=tcp://loadbalancer:443 -debug -timeout 360
            docker-compose run --rm waitforit -address=tcp://postgres:5432 -debug
            docker-compose -f docker-compose.test.yml -f docker-compose.yml run --rm app php bin/phpunit --verbose tests --log-junit /var/www/tests/artifacts/phpunit/junit.xm

        - name: Run Integrations Tests
          run: |
            sudo chmod -R 777 ./serve-web
            docker-compose -f docker-compose.test.yml -f docker-compose.yml run --rm app php bin/console doctrine:fixtures:load --group=behatTests --purge-with-truncate --no-interaction
            docker-compose -f docker-compose.test.yml -f docker-compose.yml run --rm behat --suite=local
