on:
  workflow_call:

jobs:
  test_web:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Build Dependencies
          run: make dependencies

        - name: Run Unit Tests
          run: |
            ./serve-web/generate_certs.sh
            make unit-tests

        - name: Run Integrations Tests
          run: |
            make behat-tests
