on:
  workflow_call:

jobs:
  test_web:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Build Dependencies
          run: make dependencies

        - name: Run Unit Tests
          run: |
            ./serve-web/generate_certs.sh
            docker compose -f docker-compose.yml -f docker-compose.test.yml up --build -d loadbalancer
            sleep 3
            docker compose -f docker-compose.yml -f docker-compose.test.yml exec app php bin/phpunit --verbose tests --log-junit /var/www/tests/artifacts/phpunit/junit.xml

        - name: Run Integrations Tests
          run: |
            sudo chmod -R 777 ./serve-web
            docker compose -f docker-compose.yml -f docker-compose.test.yml exec app php bin/console doctrine:fixtures:load --group=behatTests --purge-with-truncate --no-interaction
            docker compose -f docker-compose.yml -f docker-compose.test.yml exec behat --suite=local
